### ISSUE TITLE
DrvVer. Help me.

### ISSUE THREAD

**Issue by LSSoniX** [LongSoft/UBU-helpers#4]
Всем доброго здравия!
@Nikolaj Schlej 
@vit9696 
Ребят, помогите пожалуйста в DrvVer реализовать одну фишку. 
Вот здесь:
<536 build = (wchar_t*) check;
537
538 /* Printing the version found */
539 wprintf(L"     EFI GOP Driver SkyLake     - 9.0.%s\n", build);
540
>
Мне надо сравнить содержимое build с числом, чтобы выдать соответствующую запись, к примеру 
<537 if (build) <='1045'>
Понятно, что такая запись некорректна и не работает и надо преобразовать содержимое, но я не понимаю как..

**Comment by LSSoniX** [comment]
@NikolajSchlej 
Запостил, только с никами ошибся, прошу прощения, и срин не прицепояется

**Comment by LSSoniX** [comment]
Не совсем уверен, но нашел такое решение
'build = (wchar_t*)check;
int str_ver;
str_ver = wcstol(build, NULL, 10);
if (str_ver == '1086')
printf ("bla,bla\n");
'

**Comment by vit9696** [comment]
str_ver == 1086 скорее, без '.

**Comment by LSSoniX** [comment]
@vit9696 
Скорее всего. Надо будет проверить все варианты.
Спасибо.

**Comment by LSSoniX** [comment]
Проверил. В общем можно и без ' и ", хотя и с ними тоже работает.
